package com.golden_minute.nasim.domain.utils

enum class Country(country:String) {
    US("United States"),
    CA("Canada"),
    GB("United Kingdom"),
    DE("Germany"),
    FR("France"),
    ES("Spain"),
    IT("Italy"),
    RU("Russia"),
    IN("India"),
    BR("Brazil"),
    AU("Australia"),
    JP("Japan"),
    CN("China"),
    KR("South Korea"),
    MX("Mexico"),
    TH("Thailand"),
    ID("Indonesia"),
    EG("Egypt"),
    SA("Saudi Arabia"),
    ZA("South Africa"),
    NG("Nigeria"),
    PH("Philippines"),
    MY("Malaysia"),
    BD("Bangladesh"),
    GH("Ghana"),
    MA("Morocco"),
    LY("Libya"),
    DJ("Djibouti"),
    ER("Eritrea"),
    NA("Namibia"),
    CG("Republic of the Congo"),
    CD("Democratic Republic of the Congo"),
    GA("Gabon"),
    CM("Cameroon"),
    TG("Togo"),
    BJ("Benin"),
    BF("Burkina Faso"),
    ML("Mali"),
    GN("Guinea"),
    CI("Côte d'Ivoire"),
    LR("Liberia"),
    SL("Sierra Leone"),
    GU("Guinea-Bissau"),
    GW("Guinea-Bissau"),
    ST("São Tomé and Príncipe"),
    AO("Angola"),
    MZ("Mozambique"),
    ZW("Zimbabwe"),
    BW("Botswana"),
    LS("Lesotho"),
    SW("Eswatini"),
    MG("Madagascar"),
    DZ("Algeria"),
    TN("Tunisia"),
    SD("Sudan"),
    SS("South Sudan"),
    ET("Ethiopia"),
    SO("Somalia"),
    KE("Kenya"),
    UG("Uganda"),
    TZ("Tanzania"),
    MW("Malawi"),
    ZM("Zambia"),
    MO("Macau"),
    LA("Laos"),
    NP("Nepal"),
    PK("Pakistan"),
    AF("Afghanistan"),
    IR("Iran"),
    AZ("Azerbaijan"),
    AM("Armenia"),
    GE("Georgia"),
    TK("Turkmenistan"),
    UZ("Uzbekistan"),
    KG("Kyrgyzstan"),
    TJ("Tajikistan"),
    KZ("Kazakhstan"),
    MN("Mongolia"),
    TW("Taiwan"),
    HK("Hong Kong"),
    SG("Singapore"),
    VN("Vietnam"),
    KH("Cambodia"),
    BN("Brunei"),
    MM("Myanmar"),
    NZ("New Zealand"),
    PG("Papua New Guinea"),
    SB("Solomon Islands"),
    VU("Vanuatu"),
    FI("Finland"),
    SE("Sweden"),
    NO("Norway"),
    DK("Denmark"),
    IS("Iceland"),
    IE("Ireland"),
    PT("Portugal"),
    CH("Switzerland"),
    LI("Liechtenstein"),
    LU("Luxembourg"),
    BE("Belgium"),
    NL("Netherlands"),
    AT("Austria"),
    HU("Hungary"),
    CZ("Czech Republic"),
    SK("Slovakia"),
    PL("Poland"),
    RO("Romania"),
    BG("Bulgaria"),
    AL("Albania"),
    GR("Greece"),
    CY("Cyprus"),
    MLT("Malta"),
    UA("Ukraine"),
    MD("Moldova"),
    BY("Belarus"),
    LT("Lithuania"),
    LV("Latvia"),
    EE("Estonia");
}